### ISSUE TITLE
Kernel grid-stride-loops might be wrong

### ISSUE THREAD

**Issue by physicsjoke** [JuliaGPU/BinomialGPU.jl#24]
```
        tid    = threadIdx().x
        window = (blockDim().x - 1i32) * gridDim().x
        offset = (blockIdx().x - 1i32) * blockDim().x
```
should be 
```
        tid    = threadIdx().x
        window = (blockDim().x) * gridDim().x
        offset = (blockIdx().x - 1i32) * blockDim().x
```
I think a few array elements will be processed multiple times.

**Comment by physicsjoke** [comment]
@simsurace Could this be?

**Comment by simsurace** [comment]
Thanks for critically reviewing this. I think you may be right.

**Comment by simsurace** [comment]
This is a direct adaptation of [the native `rand` kernel in CUDA.jl](https://github.com/JuliaGPU/CUDA.jl/blob/aacfc36d14602ad10ae9535d2c04942713857ca8/src/random.jl#L48), so I need to rethink. Maybe it is a function of the indexing bases being different between Julia and Cuda? Not sure..

**Comment by simsurace** [comment]
I do think you are right and the implementations are wrong. I will open an issue in CUDA.jl to double-check.

**Comment by physicsjoke** [comment]
I just noticed because my code was modifying an array inplace based on the previous value and gave wrong results. Thanks for raising it in the parent package, I actually wanted a second opinion before doing so :)

**Comment by simsurace** [comment]
Indeed a bug. Will open a PR.

**Comment by simsurace** [comment]
> I just noticed because my code was modifying an array inplace based on the previous value and gave wrong results. 

How did you detect this? I would like to add a test that detects this.

**Comment by physicsjoke** [comment]
I was trying to reduce the kernel to something like this:
```
function test_ones(len::Integer)
    # The GPU kernel
    function kernel!(A)

        # grid-stride loop
        tid    = threadIdx().x
        window = (blockDim().x - 1i32) * gridDim().x
        offset = (blockIdx().x - 1i32) * blockDim().x

        while offset < length(A)
            i = tid + offset
            if i <= length(A)
                @inbounds A[i] += 1
            end
            offset += window
        end
        return nothing
    end
    
    CUDA.@sync a = CUDA.ones(UInt32, len)
    kernel = @cuda launch=false kernel!(a, b)
    config = CUDA.launch_configuration(kernel.fun; max_threads=64)
    threads = max(32, min(length(a),config.threads))
    blocks = cld(length(a), threads)
    CUDA.@sync kernel(a; threads, blocks)
    a
end
```
And then use it like this:
```
a = test_ones(100000)
a_host = Array(a)
b = findall(x->x > 2, a_host)
```
Then assert that b is empty.

Turning this into a test seems hard for any kernel where it does not matter if some elements get processed twice

**Comment by simsurace** [comment]
Yes, it seems that this window bug, although clearly wrong, could end up just wasting resources without changing the result. In that case, we don't really need a test. I thought I'd ask anyway in case you had a piece of code that would show the error with the original kernel. I think I'll merge and release this then, no need to further delay the bugfix. Thanks again for raising this issue!
