### ISSUE TITLE
Try new rand(Float32) in kernel

### ISSUE THREAD

**Issue by simsurace** [JuliaGPU/BinomialGPU.jl#7]
> So this `rand` is basically an alternative to the `GPUArrays.gpu_rand`?

This is `rand` from `Random`, made compatible by redefining `default_rng` on the device and using our own RNG. So yes, this is definitely the path forward, but we'll obviously have to flesh out the implementation by making sure the necessary APIs are GPU compatible and either overriding more calls or extending the RNG.

_Originally posted by @maleadt in https://github.com/JuliaGPU/CUDA.jl/issues/772#issuecomment-802900333_

**Comment by simsurace** [comment]
@maleadt Just to let you know: I just tried the implementation of `rand` from [CUDA.jl/#772](https://github.com/JuliaGPU/CUDA.jl/pull/772) to replace the `GPUArrays.gpu_rand(Float32, CUDA.CuKernelContext(), randstates)` by `rand(Float32)` everywhere in my kernel `kernel_BTRS`. The resulting speed is almost identical (if slightly faster) using the new function. Note that in Julia 1.5 and using the GPUArrays sampler, the speed is quite a bit faster [issue #8](https://github.com/JuliaGPU/BinomialGPU.jl/issues/8).

**Comment by maleadt** [comment]
That's good, although the memory usage of the new implementation will be (much) larger for now. I plan to revisit it before releasing CUDA 3.0 though. The performance difference with 1.5 is a problem, would be good if you could reduce to something I can have a look at :slightly_smiling_face:

**Comment by simsurace** [comment]
Yes, I will look into that and provide a minimal example!

**Comment by maleadt** [comment]
Awesome, thanks.

**Comment by simsurace** [comment]
@maleadt See [comment on issue #8](https://github.com/JuliaGPU/BinomialGPU.jl/issues/8#issuecomment-807496448)

**Comment by simsurace** [comment]
Still not fully functional, see https://github.com/JuliaGPU/CUDA.jl/pull/788#issuecomment-812031855
